name: vadavathoor_book_stall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  archive: ^3.6.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
