name: Manually Triggered Workflow
on:
  workflow_dispatch
        
jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          # optional parameters follow
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: software.zip
          directory: build/windows/x64/runner/Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookstall
          path: build/windows/x64/runner
      - name: Download a single artifact
        uses: actions/download-artifact@v4
